# Generated by Django 5.1.5 on 2025-03-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_screening', '0002_alter_resume_education_alter_resume_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='recommended_roles',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
