# Generated by Django 5.1.5 on 2025-03-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_screening', '0003_resume_recommended_roles_alter_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='recommended_roles',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
