# Generated by Django 5.1.5 on 2025-03-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_screening', '0004_alter_resume_recommended_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='sentiment',
            field=models.CharField(default='Neutral', max_length=20),
        ),
    ]
