# Generated by Django 5.1.5 on 2025-03-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_screening', '0005_resume_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='missing_skills',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
