# Generated by Django 5.1.5 on 2025-03-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_screening', '0006_resume_missing_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='missing_skills',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
